=== arnav-makkar/CN-Project/conf/config.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://sip.softphone.net"
           xmlns="http://sip.softphone.net"
           elementFormDefault="qualified">



  <!-- Simple Types -->


  <xs:simpleType name="portType">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="0"/>
      <xs:maxInclusive value="65535"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="mediaModeType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="none"/>
      <xs:enumeration value="captureAndPlayback"/>
      <xs:enumeration value="echo"/>
      <xs:enumeration value="file"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- Complex Types -->

  <xs:complexType name="configType">
    <xs:sequence>
      <xs:element name="ipAddress" type="xs:string"/>
      <xs:element name="userPart" type="xs:string"/>
      <xs:element name="domain" type="xs:string"/>
      <xs:element name="password" type="xs:string"/>
      <xs:element name="outboundProxy" type="xs:string"/>
      <xs:element name="sipPort" type="portType"/>
      <xs:element name="rtpPort" type="portType"/>
      <xs:element name="authorizationUsername" type="xs:string"/>
      <xs:element name="mediaMode" type="mediaModeType"/>
      <xs:element name="mediaDebug" type="xs:boolean"/>
      <xs:element name="mediaFile" type="xs:string"/>
      <xs:element name="enableSRTP" type="xs:boolean"/>
      <xs:element name="enableTLS" type="xs:boolean"/>
    </xs:sequence>
  </xs:complexType>

  <!-- Root Element -->

  <xs:element name="config" type="configType"/>

</xs:schema>

=== arnav-makkar/CN-Project/test-alice/conf/config.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<config xmlns="http://sip.softphone.net"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://sip.softphone.net config.xsd">
  <ipAddress>192.168.1.197</ipAddress>
  <userPart>alice</userPart>
  <domain>local</domain>
  <password>password</password>
  <outboundProxy></outboundProxy>
  <sipPort>5060</sipPort>
  <rtpPort>40000</rtpPort>
  <authorizationUsername></authorizationUsername>
  <mediaMode>captureAndPlayback</mediaMode>
  <mediaDebug>false</mediaDebug>
  <mediaFile></mediaFile>
  <enableSRTP>false</enableSRTP>
  <enableTLS>false</enableTLS>
</config>
